# Generated by Django 3.2 on 2021-04-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='value_per',
        ),
    ]
